### ISSUE TITLE
Pruned MMR doesn't removes hashes that have been committed to the base MMR.

### ISSUE THREAD

**Issue by neonknight64** [tari-project/tari#1132]
As hashes are added to the Merkel change tracker and checkpoints are committed to the base MMR, these hashes are never removed from the pruned MMR. It currently keeps a copy of all of the hashes that were added using push.

**Comment by CjS77** [comment]
From the docs of `MerkleChangeTracker`:

```
/// The basic philosophy of `MerkleChangeTracker` is as follows:
/// * Start with a 'base' MMR. For efficiency, you usually want to make this a [pruned_mmr::PrunedMmr], but it
/// doesn't have to be.
```

So this isn't required behaviour on the MCT level.

This is something that's desirable on the backend level for how we store UTXOs, but I'd argue it's not a bug of MCT per se.

**Comment by CjS77** [comment]
I've dug into this a bit, and the ChangeTracker is working as designed, if not how you were expecting it.

The failing test `check_pruning_of_pruned_mmr` does the following:
* It builds a change tracker with a limited checkpoint history (min:2 max:3)
* It then adds hashes, checkpointing occasionally. After the 5th checkpoint, the setup looks like

```text
|  xxx | xx | xxx | xx | xxx |
^               ^                        ^
b0           b1                       s
```

b0 = original base MMR state
b1 = new MMR state
s = current ChangeTracker state

This test _expects_ the b1 MMR to be a pruned MMR, i.e. nodes 0,1,2,3 are thrown away, and only the two peaks are kept. 

However, the test instantiates the ChangeTracker with a `MutableMmr` instance with a `Vec` backend, i.e. not a prunable MMR. Therefore the leaf nodes do not get discarded when the base node is updated.

But even if we did use a `PrunedHashSet` as the MMR backend, it would still keep the hashes. Here's why:

* The way `PrunedHashSet` is written, it _starts_ from a pruned state, and then subsequent pushes are stored forever. 
* So if you start a ChangeTracker with an empty `PrunedHashSet` you get no difference in behaviour from what you'd get with a 'standard' MMR: The initial (empty) state is pruned (meaning just the same as a standard MMR) and then subsequent pushes are stored.

So if we wanted the ChangeTracker to implement the behaviour that this test describes then we'd need to do the following:
* Instantiate the base MMR with a `PrunedHashSet`-backed MMR
* Change the `update_base_mmr` method in ChangeTracker to re-create the MMR afresh rather than just apply the checkpoints to the base.

**Comment by CjS77** [comment]
To proceed, I think we should 

* agree on What the desired behaviour actually is. (The disconnect results from the introduction of the commit history, which broke some of the original contracts / assumptions of the ChangeTracker code).
*  update the docs to describe the mechanics of ChangeTracker better, since it is admittedly quite confusing.
