### ISSUE TITLE
Ensure that TransactionOutput Maturity is not malleable

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1553]
Currently the Maturity of a given output is committed to when the output is added to a block in the MMR of that block. However, that means that miners could change that value without the involvement of the transaction parties.

We must find a way to fix this malleability without linking the output to the kernel.

**Comment by DavidBurkett** [comment]
There are 2 ways I can think of to commit to additional data in an output:
1. https://phyro.github.io/grinvestigation/data_commitments.html - I need to read and think through this again to make sure it's secure, but it's similar to how we implemented switch commitments in Grin
2. Currently Grin, Beam, and I suspect Tari are encrypting additional data in the bulletproofs that can be "rewound" to determine ownership of the output, keychain paths, etc. Instead of using secret keys to encrypt the data in the output, you could use a publicly known key, and encrypt a hash of an additional data structure (call it `output_data`) in the bulletproof instead. Then validation would require rewinding the bp with the publicly known key, and verifying that the rewound hash matches the hash of `output_data`

**Comment by stringhandler** [comment]
I believe this is solved through the Metadata signature on the output now
