### ISSUE TITLE
Check template block for valid transactions before sending to miner

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#1810]
Currently the mempool validates each transaction in its own as it enters the mempool. The problem is that a bunch of valid transactions does not necessary make a valid block. 

An example of this is that a we have a double spend transaction. Lets say we have tx1:
A -> B 
and tx2
A -> C
Now both transactions are valid. But both spend UTXO A. If we put both in a block, the block will be invalid. We need to check this as we construct a block.

**Comment by CjS77** [comment]
IIRC the mempool will not put the second tx in your example in the unconfirmed pool, but I may be mistaken. @neonknight64 can confirm.

**Comment by SWvheerden** [comment]
The mempool only checks a tx individually, never as a bunch.

**Comment by neonknight64** [comment]
@CjS77, I believe both transactions should be placed in the unconfirmed pool, but when the highest priority transactions are selected to be included in a block then only one can be selected and the other transaction will be discarded as a double spend when the completed block is added to the chain and the add block event is processed by the mempool. The highest_priority_txs method from the unconfirmed pool should check the inputs of a candidate transaction compared to the currently selected highest priority transactions before including it. This currently does seem to be the case and should be fixed. It should be sufficient to fix the problem in the unconfirmed pool rather than checking the template blocks.
