### ISSUE TITLE
[Mobile Epic] Back up & restore wallet

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1906]
## Ginormous wallet backup and restore epic

UX/UI for reference (exact screens for each piece of functionality mentioned inline below): https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5ecc7d974cd6d8460b0c5329

---

**Wallet backup options screen**

Not backed up yet: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

Successfully backed up with at least one method: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca9ea6b5f4b55ca37fb

**Acceptance Criteria**
- If user has no backup methods successfully configured, both options should have the red indicator per https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be
- If user has at least one method successfully configured, each should have a green checkbox next to it per https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca9ea6b5f4b55ca37fb AND any that have not yet been configured should not display any indicator at all
- “Back up with recovery phrase” should send the user to recovery phrase backup flow
- If user has already backed up to iCloud, they should be able to delete that backup by [TBD]
- If user taps either method, they should have to locally authenticate (e.g. biometrics) before being allowed to continue (unless no local auth is configured for device)

**Open question:**
@karim-tari how can a user delete their iCloud backup?

---

**Back up to iCloud/Google Drive**

@CjS77 @Jasonvdb @kukabi Do we already have a sense of how this could work? My best guess is something like this:
1. User taps Back up to iCloud from wallet backup options screen: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be
- User confirms iCloud/Drive password? (Not sure if there is a default modal apple/android pops for this)
- User sees green checkmark indicator appear in Wallet backup options screen next to the iCloud option: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca9ea6b5f4b55ca37fb

---

**Back up with recovery phrase**

**Acceptance Criteria:**
 - When user taps “Back up with recovery phrase” on backup options screen, they reach the first step of the recovery phrase backup flow, where user is prompted to write down recovery phrase: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caaa98a2d48cfa80f14
- Upon hitting continue, user is tested on recovery phrase: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa87171f477eaad4c4
    - “Confirm” button on test screen should be disabled if all 12 words appear in the gray box
    - Hint text in gray box should disappear as soon as first word is tapped
    - Tapping a word on the white bg makes it appear in the gray box instead (after any existing words there)
    - Tapping any word in the gray box moves it back to the white box
    - Gray box should slide up and down as the rows of words on the white background increase/decrease
    - When user hits Confirm, if Recovery phrase is correct, user should return to wallet backup options screen with green indicator now appearing next to “Back up with recovery phrase”
    - When user hits Confirm, if Recovery phrase is NOT correct [UX TBD]

Outstanding UX/UI @karim-tari is working on:
* Confirm seed phrase screen states (how they appear once tapped, error state, success state)
* Consider adding warning checkbox

---

**Settings screen**

**Acceptance Criteria**

- When on the profile screen, a gear icon appears in the top right
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca7f25c934857aad39a
- When user taps gear icon, the new settings screen slides up from the bottom
- On Settings screen, Back Up Wallet list item should display either red or green indicator depending on whether wallet has been backed up with at least 1 method already: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5ecc7d974cd6d8460b0c5329
- Tapping Back Up Wallet should send user to the backup options screen
- Tapping Visit Tari.com should open tari.com in an external browser window
- Tapping Contribute to Tari Aurora should open https://github.com/tari-project in an external browser window
- Tapping User Agreement, Privacy Policy, or Disclaimer should open up  tari.com/privacy_policy, tari.com/user_agreement, or tari.com/disclaimer in an external browser window

Note that all image assets available via Zeplin links as well

---

**Back up prompt modal**

**Acceptance Criteria**

- When user accepts their third tXTR transaction (that is, their first transaction NOT from the faucet), they should see the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31
- When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9
- When user reaches 25,000+ tXTR, AND it’s their 5th accepted transaction or later, display the same modal with the following copy: "Further secure your backups" "Given the amount of money in your wallet, you should password-protect your backups so they're safe even if your iCloud is compromised." "Secure Backups" "Not now" (replace iCloud with Google Drive for Android)
- The first two modals above should NOT appear if the user has already connected their cloud account.
- The third modal about encrypted backups should only appear if user has cloud backups enabled AND does not have the backups encrypted yet
- Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

---

**Restore wallet flow**

Restore wallet options screen: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca7af080a47b6f889f7 
Restore in progress screen: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8a397b248bb6a39f3

**Acceptance Criteria**
- Tapping back button should send user back to splash screen (@kukabi on Android should this maybe be an X button with the screen sliding up/down instead of left/right?)

**Open Questions**

@CjS77 @Jasonvdb @kukabi Do we have a sense of how the restore from iCloud/Drive could work? Maybe something like:
1. User taps Restore from iCloud
2. User confirms iCloud/Drive password? (Not sure if there is a default modal apple/android pops for this)
3. User sees restore in progress screen 
**Outstanding UX/UI**
* Restore process with seed phrase (they have to type it in word by word from what i understand)
* Error message and retry mechanism if restore fails

---

**Splash screen button to restore wallet**

Design TBD from @karim-tari, link will appear on splash screen similar to https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7cab4e8916298490df89

**Acceptance Criteria**
- Tapping “Restore an existing wallet” sends user to Restore wallet options screen

**Comment by philipr-za** [comment]
So just want to discuss the `Back up with recovery phrase` described above. So once again MimbleWimble is going throw a spanner in the works on this one. You cannot actually fully backup a MW wallet just using a seed phrase because in MW you require the private keys (what the seed phrase backs up) AND the values which need to be fully backed up as a list into cloud (or other) storage.

So the question I have is if we have to backup the values into some form of a file storage anyway why do we even bother with the seed phrase? We can just backup the keys with the values? I suppose there is some security value in the private keys not being stored alongside the values i.e. if the file with the values is compromised the wallet is actually still secure.

So if we still want to stick with the seed phrase we must take into account the fact that we still need to store the values in a file somewhere when backing up and load the value file when restoring while designing the UX. However, I wonder if it's not just simpler over all to rely on wallet backup/restoration being done just via a passphrase encrypted file?

Thoughts? @CjS77 @talmahaj

**Comment by Jasonvdb** [comment]
I just looked into grin and they seemed to support seed word backups. All I found is this [reddit post](https://www.reddit.com/r/grincoin/comments/ana6gb/how_does_grin_wallet_restore_work/) which isn't super helpful but the first comment mentions hiding some data inside the bulletproof.
This is only for a grin base node wallet, so I guess you can cheaply scan your local DB for commitments. Is that a mobile limitation maybe because any blockchain queries happen over the network?

**Comment by CjS77** [comment]
I wasn't aware of this trick, but the wallet can store info inside the bulletproof; and this (I suspect) is not even a consensus breaking change. The bulletproof is still valid, but the wallet will know how to extract the data from the range proof.

https://github.com/mimblewimble/grin-wallet/issues/81

This will allow us to scan the UTXO set (STXOs will have discarded the range proof in many cases)

**Comment by Jasonvdb** [comment]
I just played with Ironbelly (React native app that compiles Grin's rust wallet) just now and they managed to do a seed phrase backup and restore. https://github.com/i1skn/ironbelly

Poked around in the app looks like the restore function eventually gets to here in grin's codebase: https://github.com/mimblewimble/grin/blob/6faa0e8d75be42280f3954eebedb1676cd40bb6b/etc/gen_gen/src/bin/gen_gen.rs#L88

But then I got lost

**Comment by CjS77** [comment]
The question is whether Dalek's bulletproof library supports rewinding (which is what let's us embed data in the BP)

**Comment by CjS77** [comment]
In any event (wallet recovery is an FFI process and won't have a bearing on the UI).

Leaving recovery / restoring for the moment,
 @talmahaj, @Karim-tari, I propose some changes to the **backup** design:

## Seed phrase (backup)

We don't "Back up with the recovery phrase". 

We should just have it as "Display your seed phrase". Firstly, "seed phrase" is the term anyone familiar with crypto will be looking for. Casual users wouldn't know what "recovery phrase"  or "seed phrase" means, so we're just confusing everyone by using the former.

Saving the seed phrase is a manual pen and paper process, so "Displaying" it tells us more what it's about than "Back up with.." which suggests that the wallet is going to be doing some work in the background.

The seed phrase words should be numbered from 1 to 24 (IIRC the seed phrase is 24 words).

I don't think there's a need to test users afterwards. Or at least make it optional. My preference would be a modal that asks the user to affirm that they've written down and checked the seed phrase. Note that They can display the seed phrase whenever they like. This isn't a once-off thing.

There *must* be authentication (fingerprint / PIN) before displaying the phrase.
 
## Cloud backup

This is a pure front-end feature. No FFI required.
The wallet db file is encrypted* and saved to a user's personal cloud storage.

The design refer to iCloud; on Google, I presume this will be gDrive. We may need alternatives for people who eschew Google (or Apple for that matter) and support Dropbox / IPFS in the future.

Once permission and/or credentials have been given, the backup should proceed; and then _automatically_ backup periodically. I'd propose daily if the user's balance has changed since the last backup.

### \*What do we use as the encryption key? 

* It should not be associated with anything on the device or wallet (because then the user won't be able to restore to a clean device).
* We could ask the user for an encryption passphrase (and they must write down and/or not forget it).

**Comment by philipr-za** [comment]
> I wasn't aware of this trick, but the wallet can store info inside the bulletproof; and this (I suspect) is not even a consensus breaking change. The bulletproof is still valid, but the wallet will know how to extract the data from the range proof.
> 
> [mimblewimble/grin-wallet#81](https://github.com/mimblewimble/grin-wallet/issues/81)
> 
> This will allow us to scan the UTXO set (STXOs will have discarded the range proof in many cases)

Though just consider that a wallet cannot simply scan the UTXO set as it does not have a local copy of it. So a wallet would essentially have to sync the whole blockchain to be able to do this without fully trusting a base node.

> We should just have it as "Display your seed phrase". Firstly, "seed phrase" is the term anyone familiar with crypto will be looking for. Casual users wouldn't know what "recovery phrase" or "seed phrase" means, so we're just confusing everyone by using the former.

If we are going to just encrypt the wallet.dat then what is this seed phrase for? I don't see a purpose for it? As you say it is a term understood by people in crypto as a backup but for MW it is not a backup without the values so is that not confusing in addition to being useless without the file backup?

**Comment by CjS77** [comment]
Yes, let's assume the wallet trusts the node it's talking to

**Comment by philipr-za** [comment]
Ok, we will also have to find a way to have the node trust the wallet because it will be asked to do a lot of work so cannot do it for just any wallet.

**Comment by CjS77** [comment]
Authenticated gRPC FTW here.

But mobile wallets don't have a choice -- they'll need to find an altruistic node to handle the requests for them.

**Comment by philipr-za** [comment]
Will evaluate the feasibility of hiding data in the bulletproof and look at how much trust you have to place in a base node to make a restoration via seed phrase work.

However, with the restrictions of having to find an altruistic node (AKA run your own and get it setup with GRPC and all that) when you have the file backup option the question is why you would bother?

**Comment by Jasonvdb** [comment]
> * It should not be associated with anything on the device or wallet (because then the user won't be able to restore to a clean device).

For just iCloud it's already end to end encrypted so users would just need to login with their apple ID on their new device to be able to restore. Can still encrypt again with a password I guess but probably not necessary.
