### ISSUE TITLE
Error message for `search-stxo` and `search-utxo` says node is a Pruned Node instead of Archival Node

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#2099]
**Describe the bug**
The error message for `search-stxo` and `search-utxo` implies that an archival node is running in pruned mode when the node is still syncing.

**To Reproduce**
1. Run new archival base node
2. While blocks are syncing, call `search-stxo` or `search-utxo` for an input that exists
3. The message returned incorrectly states that the node is in pruned mode
```
Pruned node: stxo found, but block not found for stxo commitment bcd8c25773c0c28d2ad63cdf288b9b1882f2a8fc719d5c8bdd7a22fad7ca1338
```

Also: the message for `search-utxo` says "lock" instead of "block":
```
>> search-utxo bcd8c25773c0c28d2ad63cdf288b9b1882f2a8fc719d5c8bdd7a22fad7ca1338
>> Pruned node: utxo found, but lock not found for utxo commitment bcd8c25773c0c28d2ad63cdf288b9b1882f2a8fc719d5c8bdd7a22fad7ca1338
```

**Desktop (please complete the following information):**
 - OS & Version: macos 10.15.5
 - tari-base-node: commit 30062621bcfe50dc5791108ba3faf85a90631cc4

**Comment by SWvheerden** [comment]
This issue is this. 
UI asks for comms for a single bloc. 
Comms asks core for a vec of blocks.
Core asks backend for a single block. 

Is this case, the UI asked for a block.
The comms layer converted this request to a vec of 1. 
Core searched backend. 
Core returned error::notFound. **Which is corrrect
Comms layer converted this single error to a none because it returns a list. 
UI comes back as Ok(None)

In the search commands OK(None) is translated as the item was found, but it does not know which block because the item was found on the pruning horizon tip.

**Comment by delta1** [comment]
same for `search-kernel`
