### ISSUE TITLE
Check if a pending inbound transaction Output is in the chain before cancelling

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#2159]
Currently we will cancel a pending transaction if it has not completed after 3 days. However for an inbound transaction it is possible that a problem resulted in the Sender publishing the transaction but the Finalized message not reaching us. So before we totally give up on the transaction we should check with a Base Node if our output happened to be mined.

Waiting for Base Node RPC to be completed.

Related to https://github.com/tari-project/tari/issues/2137

**Comment by stringhandler** [comment]
@philipr-za can this be closed?

**Comment by SWvheerden** [comment]
Closing this. 
Although we don't do an explicit check here when we cancel a transaction, we can only really check for the single outputs we own. If we can communicate with the exact wallet that finalized the transaction, we cannot recreate the kernel fields etc. 
We can scan for the output, but since: https://github.com/tari-project/tari/pull/4464, we scan each block for outputs anyway. If an output goes missing from an erroneously canceled transaction, the utxo scanner will pick it up and add it to the OMS.
