### ISSUE TITLE
Improve initial blockchain sync with optimized receiving of blocks from peers

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2197]
This proposal is (tick applicable):

* [X] A new feature
* [X] An extension to an existing RFC/proposal (See #2113)
* [ ] An alternative approach to an existing RFC or proposal <LINK>

### Change log

| Date | Changes |
|:-----|:--------|
|      |         |

### Goals

To minimize delays between receiving blocks during the initial sync.

### Assumptions

This is dependent on RPC to be implemented.

### Abstract

Currently, one of the main reasons initial block sync is slow is due to the fact that blocks are requested in groups of 5 from a single peer, then when those blocks are received, they are processed, validated and added to the database before the next group of 5 blocks are requested form the same or another peer. This process can be enhanced by requesting and receiving blocks continuously in parallel to the validation processing.

## Description

Stream all block requests, without waiting for validation to be concluded for the next round to start. If a block in a group cannot be added to the database successfully, that group can be re-requested from a different host.

**Comment by sdbondi** [comment]
My (incomplete) proposal for the RPC-based archival block sync is detailed here:

Reading: https://developer.bitcoin.org/devguide/p2p_network.html#blocks-first

## Initial Phase - Selecting Sync Peers

We start with the assumption that the node is online in the Tari comms connectivity sense, roughly it has a few connections to other base nodes. We select all those connections and attempt to establish RPC sessions with each base node.

If the RPC session succeeds, we know:
1. The peer supports the sync protocol we want to speak
1. The ping time for the peer
1. We have some assurance that the peer is prepared to offer syncing to us (is not overloaded etc)

At this point we have rooted out peers that will not respond to sync requests and peers with slow response times (although we do not have a measure of database fetch performance, it is conceivable that this can be implemented if ever needed). 

## Are we on the same chain?

Current strategy: Peers exchange chain metadata. The peer/s that claims to have the best metadata are chosen to sync. The peer's tip header is downloaded and validated. Once validated, it is assumed that the peer is not wasting our time and has the strongest chain. The disadvantage of this approach is that nodes can lie about their chain metadata and force a node to think that it has fallen behind, therefore entering "block sync mode". A potential DoS vector.

This may be mitigated by demanding partial proof that the strongest chain can be offered (some headers near the tip, Nakamoto consensus) and perhaps comparing that with other peers to increase confidence.

**Alternate strategy**

To establish that we are on the correct chain without relying on chain metadata, all headers are downloaded and validated. 

**Optimisation**
Because headers can be validated much more quickly than full blocks, the client should do what it can to keep headers "flowing" to the node for processing. To this end, headers can be downloaded from multiple peers at once by asking a peer to stream headers in small segments. For example, peer A: "send me 5 blocks from height 0, then skip the next 5 until height 500", peer B: "send 5 blocks from height 5, then skip the next 5 and so on until height 505". 

If we have more headers than full blocks, the block bodies can begin streaming. 

The downside is that the blockchain database will need a refactor and would need to correctly handle having headers without bodies.

**Detecting chain splits**

Prior to synching full blocks, a node will send `min(n, num_blocks)` block hashes ordered in height descending order from its current tip to a peer. That peer will check the list from the first element to the last for a matching block and stream back the headers after that height until the tip. Otherwise, if no match can be found an RPC not found error is returned.
