### ISSUE TITLE
Windows 10 node not syncing 

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#2244]
Also. I take this opportunity to report the following: one of my nodes in Windows 10 is falling behind in sync for some reason. 

Sometimes it catches up and starts mining. Other times it falls behind. 
Version 0.5.4
Windows 10 on i7 9700, 16GB, 512GBSSD,
200/20 Mbps Internet 
![image0](https://user-images.githubusercontent.com/4200336/93572366-06a35700-f996-11ea-8ecd-d8eb869a93a0.jpeg)

**Comment by sdbondi** [comment]
Difficult to know without logs - but some nodes have experienced a massive reorg due to a network split. It appears that the orphan pool capacity (default: 720) is too small to handle this reorg. Putting `orphan_storage_capacity = 3000` (or some value larger than the reorg) into the `base_node.rincewind` section of the config may enable to sync to continue. 

However the sync/reorg may take a long time to process due to #2247
