### ISSUE TITLE
Unable to paste in tari console wallet on Windows 10

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#3052]
On Windows 10, user could not paste address into tari_console_wallet. 

User tried:
Ctrl+shift+v 
and also right clicking, but did not solve it.
v0.8.11

**Comment by delta1** [comment]
Do we know which terminal they were using? `cmd` or `powershell` or `windows terminal` or ?

**Comment by blobstar** [comment]
im not sure which terminal i was using (i think its cmd) but find attached a screenshot of my issue
![screenie1](https://user-images.githubusercontent.com/39502403/124396858-6fcd3e80-dd0c-11eb-89b0-9f0918437d13.jpg)

**Comment by delta1** [comment]
hi @blobstar! 

I presume you are trying to paste the emojis in to that field? I think that `cmd` probably doesn't like emojis, you could try either of these: 

- long-press the "copy emoji id" button in Aurora, that will copy the public key instead of the emojis which you should be able to paste in `cmd` 
- OR try [`windows terminal`](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) which should have emoji support 

Hope that helps, let us know!
