### ISSUE TITLE
[Console Wallet] SAF continuing for up to 28 hours after transactions are mined

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#3095]
This proposal is (tick applicable):

* [ ] A new feature
* [ ] An extension to an existing RFC/proposal <LINK>
* [X] An alternative approach to an existing RFC or proposal <LINK>

### Change log

| Date | Changes |
|:-----|:--------|
|      |         |

### Goals
Symptoms:
The sender is repeatedly sending successfully mined transactions multiple times up to 28 hours after the finalized transaction has been processed by the receiver and with both parties having detected the transaction as mined.

### Assumptions
Ideally, `Direct Send result was true`  and  `Direct Send finalize result was true` should not be followed by `Sending SAF`; with our current implementation, we have a 'fire-and-forget' peer to peer messaging implementation so this is not currently possible.

### Abstract
See _Description_ below.

## Description

The sender needs an indication that the receiver has received the finalized transaction and the sender protocol should end; a final message could be sent back to the sender in lieu of not having 'acknowledgement' in peer to peer messaging.

**Comment by philipr-za** [comment]
So the Sender only send a single Finalized Tx message to the Receiver once it gets the first reply. It will respond to repeated Replies with a Finalized tx if the Receiver keeps sending them. So there are two options here:

1. The Receiver is continuing to send replies because it hasn't received a Finalize message yet
2. The SAF system is allowing duplicates through

**Comment by hansieodendaal** [comment]
Pending further testing, lots have changed since
