### ISSUE TITLE
Message signature ("origin MAC") does not directly bind to the recipient public key

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#4139]
According to [RFC-0170](https://rfc.tari.com/RFC-0170_NetworkCommunicationProtocol.html), a message `NodeDestination` need not be a public key or cryptographically derived from a public key. This means that a message signature ("origin MAC") may not bind to the public key intended to be used (as part of an ECDH exchange against a sender-provided ephemeral public key) for the wrapping encryption of the message and signature.

It would be safer to bind the recipient public key into this signature.

**Comment by sdbondi** [comment]
Not every message has a destination which complicates things.

- `ENCRYPTED, Dest::Unknown` - [explicitly disallowed](https://github.com/tari-project/tari/blob/87a9831cbe6897000dad3bf028d91ebd35c1cfef/comms/dht/src/inbound/decryption.rs#L350)
- `CLEARTEXT, Dest::Unknown` - Used for block/txn propagation and does not include a signature (although one could be included)

- `Dest::PublicKey` - the recipient is bound in the signature

- `Dest::NodeId` - This case is interesting as any NodeId could be used. Currently, this is only used for the cleartext join/announce message. The idea is that this message is sent by the joining node and set to its own NodeId so that the message is quickly routed to the area of the network it belongs, nodes become aware of the new node. We could easily achieve the same thing by deriving the node id from the public key for routing purposes. It's tempting to just remove this variant. 
EDIT: `ENCRYPTED, Dest::NodeId` is used for wallet-to-wallet (partial) transaction propagation (a.k.a SAF message), though I suspect we could simply use the public key.

**Comment by sdbondi** [comment]
I've pushed a PR that removes the NodeId variant. @AaronFeickert Are you happy that this fixes this issue?

**Comment by AaronFeickert** [comment]
> Not every message has a destination which complicates things.
> 
> * `ENCRYPTED, Dest::Unknown` - [explicitly disallowed](https://github.com/tari-project/tari/blob/87a9831cbe6897000dad3bf028d91ebd35c1cfef/comms/dht/src/inbound/decryption.rs#L350)
> * `CLEARTEXT, Dest::Unknown` - Used for block/txn propagation and does not include a signature (although one could be included)
> * `Dest::PublicKey` - the recipient is bound in the signature
> * `Dest::NodeId` - This case is interesting as any NodeId could be used. Currently, this is only used for the cleartext join/announce message. The idea is that this message is sent by the joining node and set to its own NodeId so that the message is quickly routed to the area of the network it belongs, nodes become aware of the new node. We could easily achieve the same thing by deriving the node id from the public key for routing purposes. It's tempting to just remove this variant.
>   EDIT: `ENCRYPTED, Dest::NodeId` is used for wallet-to-wallet (partial) transaction propagation (a.k.a SAF message), though I suspect we could simply use the public key.

Yeah, the modularity of the messaging system makes analysis complicated, since it's possible to mix and match properties and parameters somewhat.

Binding specifically to a public key and performing a local identifier lookup seems reasonable to mitigate the potentials risks from this issue.

LGTM!
