### ISSUE TITLE
Allow multiple wallets to run with the same Public Key, but different tor/ip addresses

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4411]
Allow multiple wallets to run with the same Public Key, but different tor/ip addresses

**Comment by SWvheerden** [comment]
With this we have an issue with keeping track of spent UTXOs, received UTXO and which key index to use. 
This is not just a comms issue. 

A quick win here could be just to display a warning if it detects another wallet with the same pubkey on the network.

**Comment by sdbondi** [comment]
On the comms level, the following changes would be needed:
- configuration to enable multiple connections (as this is only valid for wallets, not base nodes)
- if `enable_multiple_connections == true` allow multiple connections for the same node id:
   - if a connection already exists for a node id, add to internal state without conflict resolution 
   - internal connection state maps use <NodeId, conn_id: u16> tuple as a key 
   - might be needed: if connection exists, send a protocol level ping to other existing connection to check liveness and disconnect if not live
- outbound messaging:
  -  send to all active connections for the given node id
  - allow new connections for the node id to be added on the fly
- inbound messaging:
  - key the inbound messaging listener sessions to a <NodeId, conn_id> tuple  
  - allow new connections for the node id to be added on the fly
- RPC:
  - inbound (e.g. wallet -> base node): key rpc sessions to <NodeId, conn_id> tuple
  - outbound: select an arbitrary (maybe first) connection to use, this case should never occur (see note 2).

Notes:
1. if an outbound connection already exists, continue to use that as before rather than establishing a new one
1. We'll only have multiple inbound connections to a base node from a wallet. A base node won't create outbound rpc sessions to a wallet.
1. Connection IDs should not be used/visible from the domain layer.

@SWvheerden Agree, the wallet would likely have to change a bit to detect from scanning that a utxo has been spent (if this is not already the case)

Say we have wallet A connection to any base node, and wallet B connection to any/the same base node
Wallet A spends a utxo, once mined wallet B will have to detect the spent utxo when scanning the block - if this is not already the case, shouldn't it be?

**Comment by SWvheerden** [comment]
The current wallet does not scan a block, it only scans for specific utxo's and if they are valid depending on a tip header. 

For this to work, we need the wallets to handle every block and do like a recovery on the block to find new outputs, etc. 
It's also very likely to do double spends, where more than one wallet tries to send a tx using the same inputs or even reuses the same keys for new outputs. Where the transactions are still in the mempool when they do new transactions.

**Comment by sdbondi** [comment]
Thanks for the explanation, that is tricky. The problem we have now is that this case is ~~almost certainly~~definitely going to happen.

So if I understand correctly, we'd need to change the current scanning code to include standard transactions in addition to one-sided (not just for recovery)? AFAIK, the key indexes are updated as scanning occurs so they should sync as transactions are found.

> It's also very likely to do double spends,

The base nodes will reject double spends, so I think this is fine. The wallet would be forced to wait until scanning has been completed.

> even reuses the same keys for new outputs.

Let's say we have two wallets with the same seed key $W_a$ and $W_b$. $W_b$ has just been created and still need to complete scanning (though recovery would usually have been completed prior, let's say a user is free to send a transaction with partial recovery).
$W_a$ spends $t_1 = C_1 \longrightarrow C_a$ and $t_2 = C_a \longrightarrow C_b$ (txns mined) and $W_b$ (partial recovery) spends $t_3 = C_2 \longrightarrow C_a$. This has two problems that I can think of:

1. $W_a$ will never be aware of the duplicate output with commitment $C_a$ (perhaps there is a way around this)
2. (Minor?) privacy leak, an input in $t_2$ and an output from $t_3$ can be linked. 

Anything else you can think of?

I think the reuse of output commitments exists anyway currently if users recover multiple wallets with the same seed.

**Comment by SWvheerden** [comment]
This issue has moved a bit. 
Wallets will now scan the blocks and update indexes for derived keys and updates "found inputs"
Any node can now have more than one address and its supported.

For wallets, I think the only thing missing, is that we need to make sure we contact the node at the same address they contacted us from.

**Comment by SWvheerden** [comment]
Maybe fixed, lets test

**Comment by SWvheerden** [comment]
this is partially fixed, new tracking issue here: https://github.com/tari-project/tari/issues/5914
