### ISSUE TITLE
console-wallet: seed words don't show up if using the --password flag

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4568]
When starting a new console wallet with `--password 'xxx'` the seed words do not show

**Comment by delta1** [comment]
From what I recall this was a workaround to starting the wallet without prompts in cucumber

**Comment by sdbondi** [comment]
Isn't `--non-interactive` used for that?

**Comment by delta1** [comment]
Yeah I think it predates that

**Comment by willyrgf** [comment]
Looking in the code I found this condition to show the seed words [`if interactive && recovery_seed.is_none()`](https://github.com/tari-project/tari/blob/004c219643ae42c0c1afcdb835542e53b581bfa3/applications/tari_console_wallet/src/init/mod.rs#L382). 
If I understand correctly, the problem seems to be in the condition used to set [`interactive`](https://github.com/tari-project/tari/blob/004c219643ae42c0c1afcdb835542e53b581bfa3/applications/tari_console_wallet/src/init/mod.rs#L362) that is `true` if you aren't using `--password`, instead of check on `--non-interactive` arg as said above. 

To address it we can pass a [`non_interactive_mode` like in `get_base_node_peer_config()`](https://github.com/tari-project/tari/blob/004c219643ae42c0c1afcdb835542e53b581bfa3/applications/tari_console_wallet/src/init/mod.rs#L152) that came from `cli.non_interactive_mode` to `init_wallet()` and `change_password()` then use it instead of the current `interactive`.

**Comment by sdbondi** [comment]
Yup looks like you're on the right track :+1: 

```rust
if !non_interactive_mode && recovery_seed.is_none() {
```
and clean up the  `interactive` variable.

**Comment by jorgeantonio21** [comment]
@willyrgf, I assigned this issue to you. If you need further guidance let us know.
