### ISSUE TITLE
FeePerGram values are the same for the "high" network activity

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/tari#4643]
On the Esmeralda network, the App (client) gets the same fee-per-gram values for "slow", "regular", and "fast" transactions.

**To Reproduce**
1. Call `wallet_get_fee_per_gram_stats` to get stats. If this method returns 3+ objects then the network activity is considered as "high".
2. Call `fee_per_gram_stat_get_max_fee_per_gram ` using data from 1st stat object to get fee-per-gram for "fast transaction"
3. Call `fee_per_gram_stat_get_avg_fee_per_gram ` using data from 2nd stat object to get fee-per-gram for "regular transaction"
4. Call `fee_per_gram_stat_get_avg_fee_per_gram ` using data from 3rd stat object to get fee-per-gram for "slow transaction"

**Expected behavior**
Fee-per-gram values should differ, where FPG for the first object should be the hights one and the third should be the lowest.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 (Simulator)
 - OS: iOS 15

**Comment by SWvheerden** [comment]
Calling `wallet_get_fee_per_gram_stats` with count 3, tries to see what the fee_per_gram stat will be to be mined within 3 blocks. If less than 3 object are returned, there are not enough pending transactions to fill X+ amount of blocks. 
If only 2 objects are returned, then there is enough to fill 1 block and partially fill a second block. 


As the current seed nodes say they have more than 10K transaction, they have more then enough transactions to fill more than 3 blocks. Almost all of those transactions will have the exact same fee per gram value used going by how we populated the transactions hence it returning the same value. The call works on fee_pre_gram, and not fee. This means big and small transactions have the exact same size if the same fee per gram value was used. 

This is the expected behavior for the node. I will put this under observation, once we cleared the seed nodes mempool to have less than 3 full blocks, you should see at least one of the object having a different value.

**Comment by SWvheerden** [comment]
Closing this for now. Will reopen if we can reverify this is not working correct
