### ISSUE TITLE
Pruned mode sync failure: Db transaction was too large

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4760]
Error during sync:Chain storage error: DB transaction was too large (1441 operations)
17:38 WARN  Synchronizing horizon state has failed. Chain storage error: DB transaction was too large (1441 operations)

Occurred when opening a pruned node that was synced to height 11258, trying to sync to height 16245.

Pruning horizon: 720

>> get-chain-metadata
Height of longest chain : 11258
Total accumulated difficulty: 8692910497521574169572722
Best block : fbf5672ebd57e078b4c18184bd6614a0178cdb2d4fbe3a87f97d2a5ea9b20fba
Pruning horizon : 720
Effective pruned height : 11258

**Comment by sdbondi** [comment]
We currently commit every block boundary for outputs and kernels which seems correct. You would expect this problem to be even worse for normal block sync since the whole block is in one transaction. Interesting. Will run a sync and see if anything comes up.

The current defaults are for the database to grow each time by 4Mb up to 5 times in a row before returning this error. 20 Mb seems like it should be plenty given the roughly 2mb block size. Perhaps one of these operations is larger than it should be (suspect `#1` is the accumulated data with the full deleted bitmap).
