### ISSUE TITLE
N-of-M scripts fail if more than N signatures are provided

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4820]
TariScript has n-of-m scripts that allow users to supply only n of the m signatures to "unlock" the script. 
However, if the user provides more than N, the script will fail.

**Comment by CjS77** [comment]
This is by design for now. 

How would you propose handling the general threshold case, providing n+k signatures?

Edge cases to consider:
* is there a bound on k?
* Do we need _exactly_ n valid sigs, or any n <= valid <= n+k?
* What do we do with the invalid sigs? Leave them on the stack?
* What do we do with the [0; k] additional valid sigs? Ignore them?

The answer is "depends" I guess, which infers that this is a job for additional opcodes, rather than modifying the current multisig behavior.

**Comment by stringhandler** [comment]
Ah, interesting. I agree with this approach, we should just add a note in the code that it's not supported by design

**Comment by CjS77** [comment]
Yeah, there definitely needs some docs on `check_multisig` too, explaining the purpose. I panicked for second when I saw invalid results returning `Ok(None)`, then had to go up to the calling functions to make sure that an `Ok(None)` is always treated as a fail.

Some internal comments explaining the edge cases that are caught would be helpful too (preventing multiple sigs on same pubkey etc)

**Comment by SWvheerden** [comment]
I was suspecting as much that is by design. I wanted to confirm and if we decide to keep it as such we need to put proper docs on them. 

When looking at pure opcodes, I was however expecting the script to just validate `N + K `  where `N + K <= M` and  `N + K >= N
And if a single signature is invalid, we fail the script with invalid signatures. 


The argument for allowing `N + K` is that we allow additional users to sign into the `meta_signature` on the output. 
But the argument can be made that because we only allow `N`, the parties constructing the script can just exclude members till they have `N` and no one will be wiser.

**Comment by SWvheerden** [comment]
We can close this after #4837. 
The docs internally already describe the behaviour in detail after: #4835
