### ISSUE TITLE
Add functionality for update encryption on wallet, when passphrase gets updated by user

### ISSUE THREAD

**Issue by jorgeantonio21** [tari-project/tari#5003]

**Comment by SWvheerden** [comment]
Currently, the wallet does not have the ability to change its passphrase.
If the user wants to change it, the wallet needs to be recovered to a new wallet with a new passphrase.

**Comment by AaronFeickert** [comment]
Now that [PR 5154](https://github.com/tari-project/tari/pull/5154) is merged, it's possible to support this. A few things to keep in mind:
- If the client detects that the database is encrypted using an outdated parameter set, it can update to the newest parameter set when the user enters their passphrase.
- As noted in [this comment](https://github.com/tari-project/tari/pull/5154#issuecomment-1415963906), there are persistent access attacks that could be possible under certain circumstances and threat models.

**Comment by AaronFeickert** [comment]
Some other questions to consider relating to password changes:
- Does anything need to change for `gRPC` authentication?
- Should the `CipherSeed` password be set or updated? By default, it is not, but still considered "encrypted" due to the `CipherSeed` API.
- If it is decided to allow main key resampling to mitigate the effects of persistent-access attacks, can this be done atomically to avoid the case where only some database fields are updated? The idea of atomicity still applies when updating only the secondary key, but presumably this is less likely to go awry.
