### ISSUE TITLE
Upgrade dalek fork to use newer versions

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5575]
Rand core - 0.6
rand - 0.8
Digest 0.10
sha2 - 0.10

**Comment by hansieodendaal** [comment]
See https://github.com/tari-project/curve25519-dalek/pull/2

**Comment by AaronFeickert** [comment]
A [newer PR](https://github.com/tari-project/curve25519-dalek/pull/3) indicates the update is still pending upstream verification. What needs to be checked exactly?

**Comment by hansieodendaal** [comment]
The actual requirement is to make https://github.com/tari-project/ledger work with `curve25519-dalek` and `tari_crypto`. It currently works when using `curve25519-dalek` pre-release candidate "4.0.0-rc.1". After some discussion, we agreed to use `curve25519-dalek` pre-release candidate "4.0.0-rc.3" as our base version, apply our specific changes on top and upgrade `tari_crypto` to follow suit.

**Comment by AaronFeickert** [comment]
Got it. The partial precomputation functionality in the curve library fork is now an [upstream PR](https://github.com/dalek-cryptography/curve25519-dalek/pull/546), but it's unclear if/when it would be merged, especially since it looks like they're very close to a major version release. Fortunately, it was straightforward to apply the changes, so maintaining them on the fork shouldn't be much work. (Almost all of the changes are for documentation and tests.)

**Comment by SWvheerden** [comment]
is done
