### ISSUE TITLE
Compile and install gRPC Wallet Server on android device

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#622]
Currently, the Wallet app consists of a gRPC server and an Electron App for the front-end.

Getting the server running on Android would allow us to write a custom front-end in Java/Qt/etc without having to do much to the backend.

**Comment by StriderDM** [comment]
Currently have implemented a basic Qt application (compiled for Android) that uses Qt Remote Objects to interact with a Android Foreground Service bundled within the same application. 

This is intended to then be combined with the resulting bindings (issue #656) to run the gRPC Wallet Server, as a proof of concept. 

This is due to the Android gRPC implementation provided by Google being a client-only implementation.

**Comment by CjS77** [comment]
We're using FFI directly.
