### ISSUE TITLE
Investigate strategies for running a base node implementation on iOS

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#623]
First prize:
- Run full node as gRPC service and communicate via gRPC with the front-end

2nd prize:
- Connect to trusted base node on internet via HTTPS/gRPC

3rd prize
- Janky full node that only runs when the front-end is open

**Comment by Tas4tari** [comment]
@StriderDM to provide comments by COB

**Comment by StriderDM** [comment]
**1st**
Does not appear possible due to limitations on background running restrictions in iOS.

Applications will be suspended by the OS after transitioning from the foreground to background state.

There are a few exceptions:
- Those that implement Background Fetch to fetch content in the background, however it is limited to a few seconds and execution timeline is regulated by the OS (may execute once per day).
- Audio, VOIP, Bluetooth: Those that play audio in the background, there have been instances where audio tracks containing silence was used but it makes the application highly unlikely to be accepted into the app store or worse yet, mark as malicious after being accepted. Those that listen for VOIP calls and communicate with a Bluetooth accessory are allowed to run indefinitely, however need to implement the respective API to do so.
- Newsstand and Remote Notifications: Newsstand apps need to be approved by Apple to be a major news organization, remote notifications need to come from an external source (outside of the device itself).
- Location updates: Applications which make use of the GPS as part of core functionality.

**2nd** 
Appears possible, if using iOS gRPC implementation provided by Google, it is a client-only implementation. To attempt to get a server running, which will not be officially supported by Google, potentially the most elegant solution with the lowest amount of re-implementation will be the result of Issue #656 .

**3rd** 
Probably the most likely of the above.
